version: "2"

services:
  calmcactus:
    build: .
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx, '-g', 'daemon off;']
